### ISSUE TITLE
Emoticons mis-mapped

### ISSUE THREAD

**Issue by 0rupp** [3v1n0/whatsapp-web-chrome-app#3]
I noticed some emoticons on the last page are mapped improperly. 
![emoticons2](https://cloud.githubusercontent.com/assets/7384861/6145286/868601b0-b1e0-11e4-86b4-07e1abf2ea2e.PNG)

When I write this on the web client, my mobile says:
1 2 3 4 5 6 7 8 9 0 10 1234 
So it seems the zero is at the wrong place and should be placed after the 9.

**Comment by 3v1n0** [comment]
I'm sorry, but this problem is of WhatsAppWeb itself (not of this webapp), so you should probably report to them.
